INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Books', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Eletronics', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Computer', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES('Celulares', NOW());